ontheme: jekyll-theme-minimal
title: "Sharon's portfolio" #left title of page
logo: "profile_picture.jpg" #profile pic
description: "A repository for my data science projects."
social-network-links:
email: ymsharon998@gmail.com
linkedin: [LinkedIn](https://www.linkedin.com/in/sharon-tan-107854124/)

