theme: jekyll-theme-minimal
title: "Sharon's portfolio" #left title of page
logo: "https://github.com/sharonymtan/sharonymtan.github.io/blob/main/_asset/profile_picture.jpg" #profile pic
description: "A repository for some of my data science projects."
