theme: jekyll-theme-minimal
baseurl: sharonymtan.github.io
title: "Sharon's portfolio" #left title of page
logo: "profile_picture.jpg" #profile pic
description: "A repository for my data science projects."
social-network-links:
email: "ymsharon998@gmail.com"
linkedin: [LinkedIn](https://www.linkedin.com/in/sharon-tan-107854124/)

# --- Colours / background image --- #

# Personalize the colours in your website. Colour values can be any valid CSS colour

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
