theme: jekyll-theme-minimal
title: "Sharon's Portfolio" #left title of page
logo: "/images/profile_picture_sq.jpg" #profile pic
show_downloads: false
description: "“We all are vectors. Many of us are still in search of direction”"
email: ymsharon998@gmail.com
google_analytics: G-R09D3QF7SX

